services:
  dsite:
    build: ./site
    volumes:
      - ./app:/app:ro
    restart: unless-stopped

  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - 80:80
      - 443:443
